# local_repository(
#     name = "RainbowNlp",
#     path = "/Users/azadehn/Documents/projects/workspace/rainbownlp-ea/trunk/",
# )
maven_jar(
    name = "org_hibernate_hibernate_core",
    artifact = "org.hibernate:hibernate-core:4.3.5.Final",
    sha1 = "8ba469a4749447a8e9a04f229c8017f60f9a04c9",
)
maven_jar(
    name = "mysql_mysql_connector_java",
    artifact = "mysql:mysql-connector-java:5.1.30",
    sha1 = "0203cca178350b60899be36d0e56029eca7430d8",
)
maven_jar(
    name = "org_jgrapht",
    artifact = "org.jgrapht:jgrapht-jdk1.5:0.7.3",
    sha1 = "54dc2b1b17b003b6fd62211946cb49acdc7d0364",
)
maven_jar(
    name = "weka",
    artifact = "nz.ac.waikato.cms.weka:weka-stable:3.6.11",
    sha1 = "d340b2fd101f78ce6cba814ca913a35bf96c3f94",
)
maven_jar(
    name = "org_slf4j_slf4j_log4j12",
    artifact = "org.slf4j:slf4j-log4j12:1.7.5",
    sha1 = "6edffc576ce104ec769d954618764f39f0f0f10d",
)
maven_jar(
    name = "apache_stanbol",
    artifact = "org.apache.stanbol:org.apache.stanbol.commons.opennlp:0.12.0",
    sha1 = "f328af329ebd86931c99a212219da35ddb277496",
)
maven_jar(
    name = "opennlp",
    artifact = "org.apache.opennlp:opennlp-uima:1.5.3",
)
maven_jar(
    name = "opennlp_tools",
    artifact = "org.apache.opennlp:opennlp-tools:1.8.0",
)
maven_jar(
    name = "stanford_core_nlp",
    artifact = "edu.stanford.nlp:stanford-corenlp:3.3.1",
    sha1 = "0c885620c5c15ddaee133fad8d307324197fb148",
)
maven_jar(
    name = "mallet",
    artifact = "cc.mallet:mallet:2.0.7",
    sha1 = "11f69356b961fe34cc256908a22b90e135db7d2a",
)
maven_jar(
    name = "apache_commons",
    artifact = "org.apache.commons:commons-math:2.0",
    sha1 = "c4722aba0d2af91c615fe8892fa9e01b3394516b",
)
maven_jar(
    name = "amazonaws",
    artifact = "com.amazonaws:aws-java-sdk:1.7.9",
    sha1 = "de51e9b2116e378a73fd24466205b22dc67b0b34",
)
maven_jar(
    name = "springframework_boot",
    artifact = "org.springframework:spring-context:4.3.8.RELEASE",
)
maven_jar(
    name = "junit",
    artifact = "junit:junit:4.12",
)
maven_jar(
    name = "ch_logback",
    artifact = "ch.qos.logback:logback-core:1.2.3",
)
maven_jar(
    name = "hibernate_jpa",
    artifact = "org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final",
	sha1 = "5e731d961297e5a07290bfaf3db1fbc8bbbf405a",
)
maven_jar(
    name = "dom4j",
    artifact = "dom4j:dom4j:1.6.1",
	sha1 = "5d3ccc056b6f056dbf0dddfdf43894b9065a8f94",
)
maven_jar(
    name = "hibernate_annotations",
    artifact = "org.hibernate.common:hibernate-commons-annotations:4.0.4.Final",
	sha1 = "f1af75eca4e13ac0578750a497159695feceebfc",
)
maven_jar(
    name = "jboss_logger",
    artifact = "org.jboss.logging:jboss-logging:3.3.1.Final",
	sha1 = "c46217ab74b532568c0ed31dc599db3048bd1b67",
)
maven_jar(
    name = "hibernate_envers",
    artifact = "org.hibernate:hibernate-envers:4.3.10.Final",
	sha1 = "61ec59165771b90cea5a59418f60aefa123b33f4",
)
maven_jar(
    name = "jta",
    artifact = "javax.transaction:jta:1.1",
	sha1 = "2ca09f0b36ca7d71b762e14ea2ff09d5eac57558",
)
maven_jar(
    name = "log4j_over_slf4j",
    artifact = "org.slf4j:log4j-over-slf4j:1.6.4",
	sha1 = "ddfe7c1606881837039903db7bee486c1336c15e",
)
maven_jar(
    name = "slf4j_api",
    artifact = "org.slf4j:slf4j-api:1.6.4",
	sha1 = "2396d74b12b905f780ed7966738bb78438e8371a",
)
maven_jar(
    name = "javassist",
    artifact = "org.javassist:javassist:3.18.1-GA",
	sha1 = "d9a09f7732226af26bf99f19e2cffe0ae219db5b",
)
maven_jar(
    name = "antlr",
    artifact = "antlr:antlr:2.7.7",
	sha1 = "83cd2cd674a217ade95a4bb83a8a14f351f48bd0",
)
